spring:
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/db_txjg?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  mvc:
  #    static-path-pattern: classpath:/static/**

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect


  thymeleaf:
    cache: false #关闭缓存
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 9091